### ISSUE TITLE
Update files with R code to be executable

### ISSUE THREAD

**Issue by schnaitter** [quadriga-dk/Tabelle-Fallstudie-1#164]
These sections contain R code:
- [ ] 6.2
- [ ] 6.3
- [ ] 7.1
- [ ] 7.2

**Comment by schnaitter** [comment]
The frontmatter is:
```
---
jupytext:
  formats: md:myst
  text_representation:
    extension: .md
    format_name: myst
kernelspec:
  display_name: R
  language: R
  name: ir
---
```
